tap 'caskroom/cask', 'git@github.com:caskroom/homebrew-cask'
tap 'caskroom/versions'
#tap 'docmunch/pdftk'
#tap 'gbeine/homebrew-java'
tap 'homebrew/bundle'
tap 'homebrew/command-not-found'
#tap 'homebrew/emacs'
#tap 'homebrew/fuse'
#tap 'homebrew/science'
tap 'homebrew/services'
#tap 'homebrew/versions'
#tap 'homebrew/homebrew-x11'
#tap 'jonof/kenutils'

cask 'java'
cask 'osxfuse'
cask 'xquartz'

brew 'openssl'
brew 'openssh', args: ['with-brewed-openssl', 'with-keychain-support']
brew 'curl', args: ['with-ssl', 'with-libssh2']
brew 'svn'
brew 'parallel'  # Install before moreutils that also different `parallel` command.

brew 'ack'
brew 'advancecomp'
brew 'ag'
brew 'ant'
brew 'antiword'
brew 'apache-spark'
brew 'apg'
brew 'archey'
brew 'arpack'
brew 'aspell'
brew 'autoconf'
#brew 'autojump'  # fasd
brew 'automake'
#brew 'awscli'  # pyenv
#brew 'aws-shell'  # pyenv
brew 'bash'
brew 'binutils'
brew 'c-ares'
brew 'cairo'
brew 'cask'
brew 'ccache'
brew 'certbot'
brew 'cheat'
brew 'checkstyle'
brew 'cloog'
brew 'cmake'
brew 'colordiff'
brew 'cookiecutter'
brew 'coreutils' #, args: ['default-names']
brew 'cowsay'
brew 'cscope'
brew 'd-bus'
brew 'daq'
brew 'docmunch/pdftk/pdftk'
brew 'dos2unix'
brew 'direnv'
brew 'docker-clean'
brew 'ecj'
brew 'editorconfig'
brew 'emacs', args: ['with-imagemagick', 'with-modules']
brew 'epstool'
brew 'faac'
brew 'fasd'
brew 'ffmpeg'
brew 'fftw'
brew 'figlet'
brew 'findutils' #, args: ['default-names']
brew 'fontconfig'
brew 'fortune'
brew 'freetype'
brew 'fzf'
brew 'gawk'
brew 'gbeine/homebrew-java/postgresql-jdbc'
brew 'gcc', args: ['with-all-languages']
brew 'gd'
brew 'gdb'
brew 'gdbm'
brew 'geoip'
brew 'gettext'
brew 'ghostscript'
brew 'git', args: ['with-brewed-curl', 'with-brewed-openssl', 'with-brewed-svn', 'with-gettext', 'with-pcre', 'with-persistent-https']
brew 'git-ftp'
brew 'git-standup'
brew 'glpk'
brew 'gl2ps'
brew 'glib'
brew 'gmp'
brew 'gpg-agent'
brew 'gnu-getopt'
brew 'gnu-indent' #, args: ['default-names']
brew 'gnu-sed' #, args: ['default-names']
brew 'gnu-tar' #, args: ['default-names']
brew 'gnu-which' #, args: ['with-default-names']
brew 'gnuplot', args: ['with-qt', 'with-x11']
brew 'gnutls'
brew 'go'
brew 'gobject-introspection'
brew 'graphicsmagick'
brew 'graphviz'
brew 'gwt'
brew 'hadoop'
brew 'hdf5'
brew 'bash-completion'
brew 'brew-cask-completion'
brew 'bundler-completion'
brew 'docker-completion'
brew 'docker-compose-completion'
brew 'docker-machine-completion'
brew 'gem-completion'
brew 'homesick-completion'
brew 'launchctl-completion'
# brew 'maven-completion'
brew 'octave', args: ['with-gui']
brew 'open-completion'
brew 'pip-completion'
brew 'qhull'
brew 'qrupdate'
brew 'ruby-completion'
brew 'sonar-completion'
brew 'stormssh-completion'
brew 'suite-sparse'
brew 'vagrant-completion'
brew 'veclibfort'
brew 'tmuxinator-completion'

brew 'diffutils'
brew 'ed'#, args: ['with-default-names']
brew 'file-formula'
brew 'gpatch'
brew 'grep'#, args: ['with-default-names']
brew 'gzip'
brew 'less'
brew 'lsof'
brew 'm4'
brew 'make'
brew 'nano'
brew 'rsync'
brew 'screen'
brew 'tcpdump'
brew 'units'
brew 'unzip'
brew 'homebrew/science/r'
brew 'homebrew/science/suite-sparse421'
brew 'homebrew/emacs/dash-emacs'
brew 'homebrew/emacs/git-messenger'
brew 'homebrew/emacs/git-modes'
brew 'homebrew/emacs/homebrew-mode'
brew 'homebrew/emacs/hydra-emacs'
brew 'homebrew/emacs/inf-ruby'
brew 'homebrew/emacs/json-mode'
brew 'homebrew/emacs/json-reformat'
brew 'homebrew/emacs/json-snatcher'
brew 'homebrew/emacs/markdown-mode'
brew 'homebrew/emacs/org-mode'
brew 'homebrew/emacs/pandoc-mode'
brew 'homebrew/emacs/popup'
brew 'homebrew/emacs/solarized-emacs'
brew 'homebrew/emacs/yaml-mode'
brew 'homebrew/fuse/ntfs-3g'
brew 'homebrew/fuse/sshfs'
brew 'homebrew/gui/gsmartcontrol'
brew 'homebrew/versions/perl518'
brew 'homebrew/homebrew-x11/gv'
brew 'httpie'
brew 'hub'
brew 'hunspell'
brew 'icdiff'
brew 'icu4c'
brew 'imagemagick'
brew 'isl'
brew 'gifsicle'
brew 'jbig2dec'
brew 'jenv'
brew 'jhead'
brew 'jonof/kenutils/pngout'
brew 'jpeg'
brew 'jpegoptim'
brew 'jq'
brew 'keychain'
brew 'lame'
# brew 'lastpass-cli', args: ['with-doc']
brew 'libdnet'
brew 'libdvdcss'
brew 'libffi'
brew 'libgcrypt'
brew 'libgpg-error'
brew 'libmpc'
brew 'libpng'
brew 'libsodium'
brew 'libtasn1'
brew 'libtiff'
brew 'libtool'
brew 'libvo-aacenc'
brew 'libyaml'
brew 'little-cms2'
brew 'lua'
brew 'luajit'
brew 'lynx'
brew 'lzip'
brew 'mackup'
brew 'macvim', args: ['with-override-system-vim']
brew 'makedepend'
brew 'mas'
# brew 'maven'
# brew 'mercurial'
brew 'mkdocs'
brew 'mongodb', args: ['with-openssl']
brew 'moreutils'
brew 'mpfr'
brew 'mysql-connector-c'
brew 'nettle'
brew 'nmap'
brew 'node'
brew 'openjpeg'
brew 'openssl'
brew 'optipng'
brew 'pandoc'
brew 'pandoc-citeproc'
brew 'pcre'
# brew 'pinentry-mac' # Use GPG Suite instead.
brew 'pixman'
brew 'pkg-config'
brew 'plotutils'
brew 'pngcrush'
brew 'pngquant'
brew 'poppler'
brew 'postgresql'
brew 'pstoedit'
brew 'pv'
brew 'pwgen'
brew 'pyenv'
brew 'pyenv-ccache'
brew 'pyenv-pip-migrate'
brew 'pyenv-virtualenv'
brew 'pyenv-which-ext'
brew 'pyqt'
brew 'python'
brew 'qscintilla2'
brew 'qt'
brew 'rbenv'
brew 'readline'
brew 'rename'
brew 'ruby-build'
brew 'scala'
brew 'screenfetch'
brew 'shellcheck'
brew 'sip'
brew 'snort'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'subversion'
brew 'szip'
brew 'tbb'
brew 'tesseract'
brew 'texi2html'
brew 'texinfo'
#brew 'thefuck'  # pyenv
brew 'the_silver_searcher'
brew 'tivodecode'
brew 'tmux'
brew 'tomcat'
brew 'trash'
brew 'tree'
brew 'vim', args: ['override-system-vi']
brew 'vitorgalvao/tiny-scripts/cask-repair'
brew 'watch'
brew 'wdiff', args: ['with-gettext']
brew 'webkit2png'
brew 'wget'
brew 'wine'
brew 'winetricks'
brew 'wireshark'
brew 'x264'
brew 'xvid'
brew 'xz'
brew 'yasm'
brew 'youtube-dl'
brew 'zopfli'
brew 'zsh'

cask '1password' #, args: { appdir: '/Applications' }
cask 'adobe-reader'
# cask 'anaconda'
# cask 'appcleaner'
cask 'appfresh'
cask 'apptrap'
cask 'aquamacs'
cask 'avast'
cask 'backblaze'
cask 'bartender'
cask 'bbedit'
cask 'bettertouchtool'
cask 'betterzip'
cask 'betterzipql'
# cask 'bibdesk'
# cask 'bittorrent-sync'
cask 'box-sync'
#cask 'caffeine'
cask 'cakebrew'
cask 'carbon-copy-cloner'
cask 'carmaintenance'
cask 'cheatsheet'
cask 'choosy'
cask 'chrome-remote-desktop-host'
cask 'chromium'
cask 'coconutBattery'
cask 'controlplane'
cask 'cord'
# cask 'crashplan'
cask 'ctivo'
cask 'dash'
cask 'dbeaver-enterprise'
cask 'dbvisualizer'
# cask 'disk-inventory-x'
cask 'diskmaker-x'
cask 'diskwave'
cask 'dnscrypt'
cask 'docker'
cask 'docker-toolbox'
cask 'dockertoolbox'
cask 'dropbox'
cask 'duplicate-annihilator'
# cask 'eclipse-java'
cask 'emacs'
cask 'evernote'
cask 'filebot'
cask 'filezilla'
cask 'firefox'
cask 'fitbit-connect'
# cask 'flash'
cask 'flashlight'
cask 'flickr-uploadr'
cask 'flux'
cask 'ganttproject'
cask 'geektool'
cask 'gephi'
cask 'gimp'
# cask 'github-desktop'
cask 'goodsync'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'google-photos-backup'
cask 'gpgtools'
cask 'grandperspective'
cask 'growlnotify'
cask 'growlvoice'
cask 'handbrake'
cask 'handylock'
cask 'ibettercharge'
cask 'imageoptim'
cask 'iterm2'
cask 'jing'
cask 'joinme'
cask 'karabiner'
cask 'keka'
cask 'keybase'
cask 'kindle'
cask 'kite'
cask 'lastpass'
cask 'libdvdcss'
cask 'libreoffice'
cask 'logitech-control-center'
cask 'logitech-myharmony'
cask 'logitech-unifying'
cask 'lyx'
cask 'macdown'
cask 'macfusion'
cask 'macfusion', args: { appdir: '/Application' }
cask 'mactex'
cask 'macx-youtube-downloader'
cask 'mailbox'
cask 'makemkv'
cask 'malwarebytes-anti-malware'
cask 'marked'
cask 'mendeley-desktop'
cask 'metaz'
cask 'microsoft-office'
cask 'mysqlworkbench'
cask 'no-ip-duc'
cask 'notebook'
cask 'omnidisksweeper'
cask 'omnifocus'
cask 'onyx'
cask 'osxfuse'
cask 'oversight'
cask 'p4merge'
cask 'pacifist'
# cask 'picasa'
cask 'podcastmenu'
cask 'prey'
cask 'pycharm'
# cask 'pycharm-ce'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
# cask 'quicksilver'
# cask 'rstudio'
cask 'send-to-kindle'
cask 'sequel-pro'
cask 'shazzlemailclient'
cask 'silverlight'
cask 'skyfonts'
cask 'skype'
cask 'slack'
cask 'slimbatterymonitor'
cask 'snowflake-snowsql'
cask 'sookasa'
cask 'sourcetree'
cask 'spectacle'
cask 'spotdox'
cask 'sshfs'
cask 'steam'
cask 'subler'
cask 'sublime-text'
cask 'suspicious-package'
# cask 'teamviewer'
# cask 'tether'
cask 'texshop'
cask 'texstudio'
cask 'the-unarchiver'
cask 'thunderbird'
cask 'tonido'
cask 'tonidosync'
# cask 'tower'
cask 'transmission'
cask 'transmit'
cask 'tresorit'
cask 'tunnelblick'
cask 'unison'
cask 'virtualbox'
cask 'vlc'
cask 'webpquicklook'
cask 'wireshark'
cask 'xquartz'
cask 'yujitach-menumeters'
cask 'zotero'

