---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
DISABLE:
  - ACTION # FIXME: Figure out why doesn't run!
  - EDITORCONFIG # FIXME: Figure out why not working!?
  - PYTHON
DISABLE_LINTERS:
  - BASH_SHELLCHECK # FIXME: Related to ACTION error?
FILEIO_REPORTER: true
JSON_V8R_DISABLE_ERRORS: true
LINTER_RULES_PATH: .
SHOW_ELAPSED_TIME: true
SPELL_MISSPELL_FILTER_REGEX_EXCLUDE: (bash/.bash/aliases)
# FIXME: Add v8r schemas for:
# * .github/mergify.yml
# * .ntfy.yml - https://ntfy.readthedocs.io/en/latest/#backends - do it myself? or ignore
