encryption = "age"

[data]
    name = "Name"
    email = "name@example.com"
    defaultkey = "123"
    githubemail = "name@example.com"
    opaccount = "opaccount"
    slackrecipient = "slackrecipient"
    slacktoken = "123"
    work = false
    # Personal machine configuration
    test = true

[age]
    # passphrase = true
    identity = "~/.config/chezmoi/key.txt"
    recipient = "123"

[diff]
    command = "vi"
    args = ["-d"]

[edit]
    command = "vi"
    args = []

[git]
    autoCommit = false
    autoPush = false

[gpg]
    args = ["--quiet"]
    symmetric = true

[[textconv]]
    pattern = "**/*.plist"
    command = "plutil"
    args = ["-convert", "xml1", "-o", "-", "-"]
