---

ignore-failures:

    python:
        - async-generator
        - async-timeout
        - cycler
        - entrypoints
        - jupyter-contrib-core
        - jupyter-contrib-nbextensions
        - jupyter-highlight-selected-word
        - jupyter-latex-envs
        - jupyter-nbextensions-configurator
        - markupsafe
        - mccabe
        - mistune
        - patsy
        - pickleshare
        - pylev
        - send2trash
        - testpath
        - webencodings

    ruby:
        - ruby-lint
