[global]
# If set to true, also look for and load .env files on top of the .envrc files.
# If both .envrc and .env files exist, the .envrc will always be chosen first.
load_dotenv = true

[whitelist]
exact = [
      "/Users/ftod/.envrc",
      "/Users/ftod/GitHub/dotfiles/.envrc",
      "/Users/ftod/GitHub/dotfiles/direnv/.envrc",
      "/Users/ftod/GitHub/mac-playbook/.envrc",
      "/Users/ftod/GitHub/proinsias.github.io/.envrc"
]
