---
# Based on https://github.com/geerlingguy/mac-dev-playbook/blob/master/.github/workflows/ci.yml.

######################################################################
## minute         0-59
## hour           0-23
## day of month   1-31
## month          1-12
## day of week    0-7
######################################################################

name: Test Chezmoi Dotfiles
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 1 2 * * 3
  # Run workflow manually (without waiting for the cron to be called),
  # through the Github Actions Workflow page directly.
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        shell: [bash, zsh]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup temporary HOME and copy blank config
        run: |
          mkdir -p "${TEST_HOME}/.config/chezmoi"
        env:
          TEST_HOME: ${{ runner.temp }}/testhome

      - name: Install chezmoi
        run: |
          curl -fsSL https://get.chezmoi.io | sh -s -- -b "${TEST_HOME}/bin"
          echo "${TEST_HOME}/bin" >> "${GITHUB_PATH}"
        env:
          TEST_HOME: ${{ runner.temp }}/testhome

      - name: Initialize chezmoi
        run: |
          chezmoi init --source="$(pwd)" --destination="${TEST_HOME}" \
              --promptDefaults
        env:
          TEST_HOME: ${{ runner.temp }}/testhome

      - name: Run chezmoi doctor
        run: |
          chezmoi doctor --verbose

      - name: Apply dotfiles into temp home
        run: |
          chezmoi apply --verbose

      - name: Verify dotfiles consistency
        run: |
          chezmoi verify --verbose

      - name: Smoke test shell startup
        run: |
          echo "--- Running smoke test for ${{ matrix.shell }} ---"
          if [ "${{ matrix.shell }}" = "zsh" ]; then
            # Some runners don't have zsh preinstalled
            if ! command -v zsh >/dev/null; then
              echo "Installing zsh..."
              if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
                sudo apt-get update && sudo apt-get install -y zsh
              else
                brew install zsh
              fi
            fi
            ZDOTDIR="${TEST_HOME}" HOME="${TEST_HOME}" zsh -i -c 'echo "zsh ${ZSH_VERSION}"; alias | head -n 10'
          else
            HOME="${TEST_HOME}" bash -i -c 'echo "bash ${BASH_VERSION}"; alias | head -n 10'
          fi
        shell: bash
        env:
          TEST_HOME: ${{ runner.temp }}/testhome
